### ISSUE TITLE
Day 29 Lab - App crashes when attempting to add employee after one is removed

### ISSUE THREAD

**Issue by elaewin** [luayyounus/EmployeesList#13]
When I attempt to add another employee after I've used the delete feature, the app crashes when I hit the save button. Attempting to run the app again causes an instant crash at line 22 of `EmployeeDatabase.m`. 

This does not occur every time. Sometimes I have to go through the add/remove process twice before the app crashes.

**Comment by luyounus** [comment]
I tracked the application and had Adam taking a look at it. It's crashing for an unknown reason and I'm unable to resolve it.
